In [1]:
import requests
import pandas as pd
import io

def descargar_zona_cuadricula(fecha_inicio, fecha_fin, mag_min, min_lat, max_lat, min_lon, max_lon):
    url = "https://earthquake.usgs.gov/fdsnws/event/1/query"
    params = {
        "format": "csv",
        "starttime": fecha_inicio,
        "endtime": fecha_fin,
        "minmagnitude": mag_min,
        # Filtros geográficos:
        "minlatitude": min_lat,
        "maxlatitude": max_lat,
        "minlongitude": min_lon,
        "maxlongitude": max_lon
    }
    
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return pd.read_csv(io.StringIO(response.text))
    else:
        print(f"Error: {response.status_code}")
        return None

In [2]:
import time
import pandas as pd

# Definimos las coordenadas de la cuadrícula de Japón
min_lat_japon = 24.0
max_lat_japon = 46.0
min_lon_japon = 122.0
max_lon_japon = 146.0

fechas = pd.date_range(start="2020-01-01", end="2024-01-01", freq="MS")
lista_df = []

print("Iniciando extracción mes a mes para Japón...")

for i in range(len(fechas) - 1):
    inicio = fechas[i].strftime("%Y-%m-%d")
    fin = fechas[i+1].strftime("%Y-%m-%d")
    
    print(f"Descargando {inicio} a {fin}...", end=" ")
    
    df_mes = descargar_zona_cuadricula(
        inicio, fin, 4.0,  # Nota: Subido a 4.0 (leer consejo abajo)
        min_lat_japon, max_lat_japon, 
        min_lon_japon, max_lon_japon
    )
    
    if df_mes is not None:
        print(f"{len(df_mes)} sismos.")
        lista_df.append(df_mes)
        
    time.sleep(0.5)

if lista_df:
    df_japon_total = pd.concat(lista_df, ignore_index=True)
    df_japon_total = df_japon_total.drop_duplicates(subset='id')
    df_japon_total = df_japon_total.sort_values(by='time').reset_index(drop=True)
    
    print(f"\n¡Éxito Total! Se han descargado y unificado {len(df_japon_total)} sismos de Japón.")
    df_japon_total.to_csv("catalogo_japon_2020_2023.csv", index=False)

Iniciando extracción mes a mes para Japón...
Descargando 2020-01-01 a 2020-02-01... 70 sismos.
Descargando 2020-02-01 a 2020-03-01... 71 sismos.
Descargando 2020-03-01 a 2020-04-01... 56 sismos.
Descargando 2020-04-01 a 2020-05-01... 79 sismos.
Descargando 2020-05-01 a 2020-06-01... 81 sismos.
Descargando 2020-06-01 a 2020-07-01... 126 sismos.
Descargando 2020-07-01 a 2020-08-01... 77 sismos.
Descargando 2020-08-01 a 2020-09-01... 70 sismos.
Descargando 2020-09-01 a 2020-10-01... 74 sismos.
Descargando 2020-10-01 a 2020-11-01... 56 sismos.
Descargando 2020-11-01 a 2020-12-01... 72 sismos.
Descargando 2020-12-01 a 2021-01-01... 63 sismos.
Descargando 2021-01-01 a 2021-02-01... 64 sismos.
Descargando 2021-02-01 a 2021-03-01... 84 sismos.
Descargando 2021-03-01 a 2021-04-01... 66 sismos.
Descargando 2021-04-01 a 2021-05-01... 89 sismos.
Descargando 2021-05-01 a 2021-06-01... 160 sismos.
Descargando 2021-06-01 a 2021-07-01... 90 sismos.
Descargando 2021-07-01 a 2021-08-01... 83 sismos.
Descargando 2021-08-01 a 2021-09-01... 114 sismos.
Descargando 2021-09-01 a 2021-10-01... 68 sismos.
Descargando 2021-10-01 a 2021-11-01... 75 sismos.
Descargando 2021-11-01 a 2021-12-01... 109 sismos.
Descargando 2021-12-01 a 2022-01-01... 178 sismos.
Descargando 2022-01-01 a 2022-02-01... 105 sismos.
Descargando 2022-02-01 a 2022-03-01... 111 sismos.
Descargando 2022-03-01 a 2022-04-01... 170 sismos.
Descargando 2022-04-01 a 2022-05-01... 118 sismos.
Descargando 2022-05-01 a 2022-06-01... 100 sismos.
Descargando 2022-06-01 a 2022-07-01... 102 sismos.
Descargando 2022-07-01 a 2022-08-01... 98 sismos.
Descargando 2022-08-01 a 2022-09-01... 135 sismos.
Descargando 2022-09-01 a 2022-10-01... 118 sismos.
Descargando 2022-10-01 a 2022-11-01... 104 sismos.
Descargando 2022-11-01 a 2022-12-01... 86 sismos.
Descargando 2022-12-01 a 2023-01-01... 79 sismos.
Descargando 2023-01-01 a 2023-02-01... 68 sismos.
Descargando 2023-02-01 a 2023-03-01... 77 sismos.
Descargando 2023-03-01 a 2023-04-01... 76 sismos.
Descargando 2023-04-01 a 2023-05-01... 83 sismos.
Descargando 2023-05-01 a 2023-06-01... 125 sismos.
Descargando 2023-06-01 a 2023-07-01... 86 sismos.
Descargando 2023-07-01 a 2023-08-01... 76 sismos.
Descargando 2023-08-01 a 2023-09-01... 72 sismos.
Descargando 2023-09-01 a 2023-10-01... 125 sismos.
Descargando 2023-10-01 a 2023-11-01... 263 sismos.
Descargando 2023-11-01 a 2023-12-01... 73 sismos.
Descargando 2023-12-01 a 2024-01-01... 89 sismos.

¡Éxito Total! Se han descargado y unificado 4614 sismos de Japón.

In [3]:
import time
import pandas as pd

# Definimos las coordenadas de la cuadrícula de Chile
min_lat_chile = -56.0
max_lat_chile = -17.0
min_lon_chile = -76.0
max_lon_chile = -65.0

fechas = pd.date_range(start="2020-01-01", end="2024-01-01", freq="MS")
lista_df = []

print("Iniciando extracción mes a mes para Chile...")

for i in range(len(fechas) - 1):
    inicio = fechas[i].strftime("%Y-%m-%d")
    fin = fechas[i+1].strftime("%Y-%m-%d")
    
    print(f"Descargando {inicio} a {fin}...", end=" ")
    
    df_mes = descargar_zona_cuadricula(
        inicio, fin, 4.0, # Nota: Subido a 4.0
        min_lat_chile, max_lat_chile, 
        min_lon_chile, max_lon_chile
    )
    
    if df_mes is not None:
        print(f"{len(df_mes)} sismos.")
        lista_df.append(df_mes)
        
    time.sleep(0.5)

if lista_df:
    df_chile_total = pd.concat(lista_df, ignore_index=True)
    df_chile_total = df_chile_total.drop_duplicates(subset='id')
    df_chile_total = df_chile_total.sort_values(by='time').reset_index(drop=True)
    
    print(f"\n¡Éxito Total! Se han descargado y unificado {len(df_chile_total)} sismos de Chile.")
    df_chile_total.to_csv("catalogo_chile_2020_2023.csv", index=False)

Iniciando extracción mes a mes para Chile...
Descargando 2020-01-01 a 2020-02-01... 79 sismos.
Descargando 2020-02-01 a 2020-03-01... 42 sismos.
Descargando 2020-03-01 a 2020-04-01... 72 sismos.
Descargando 2020-04-01 a 2020-05-01... 77 sismos.
Descargando 2020-05-01 a 2020-06-01... 73 sismos.
Descargando 2020-06-01 a 2020-07-01... 59 sismos.
Descargando 2020-07-01 a 2020-08-01... 83 sismos.
Descargando 2020-08-01 a 2020-09-01... 50 sismos.
Descargando 2020-09-01 a 2020-10-01... 106 sismos.
Descargando 2020-10-01 a 2020-11-01... 75 sismos.
Descargando 2020-11-01 a 2020-12-01... 78 sismos.
Descargando 2020-12-01 a 2021-01-01... 112 sismos.
Descargando 2021-01-01 a 2021-02-01... 83 sismos.
Descargando 2021-02-01 a 2021-03-01... 66 sismos.
Descargando 2021-03-01 a 2021-04-01... 53 sismos.
Descargando 2021-04-01 a 2021-05-01... 87 sismos.
Descargando 2021-05-01 a 2021-06-01... 86 sismos.
Descargando 2021-06-01 a 2021-07-01... 70 sismos.
Descargando 2021-07-01 a 2021-08-01... 94 sismos.
Descargando 2021-08-01 a 2021-09-01... 78 sismos.
Descargando 2021-09-01 a 2021-10-01... 94 sismos.
Descargando 2021-10-01 a 2021-11-01... 63 sismos.
Descargando 2021-11-01 a 2021-12-01... 61 sismos.
Descargando 2021-12-01 a 2022-01-01... 72 sismos.
Descargando 2022-01-01 a 2022-02-01... 81 sismos.
Descargando 2022-02-01 a 2022-03-01... 60 sismos.
Descargando 2022-03-01 a 2022-04-01... 69 sismos.
Descargando 2022-04-01 a 2022-05-01... 79 sismos.
Descargando 2022-05-01 a 2022-06-01... 80 sismos.
Descargando 2022-06-01 a 2022-07-01... 70 sismos.
Descargando 2022-07-01 a 2022-08-01... 69 sismos.
Descargando 2022-08-01 a 2022-09-01... 67 sismos.
Descargando 2022-09-01 a 2022-10-01... 78 sismos.
Descargando 2022-10-01 a 2022-11-01... 68 sismos.
Descargando 2022-11-01 a 2022-12-01... 69 sismos.
Descargando 2022-12-01 a 2023-01-01... 73 sismos.
Descargando 2023-01-01 a 2023-02-01... 70 sismos.
Descargando 2023-02-01 a 2023-03-01... 90 sismos.
Descargando 2023-03-01 a 2023-04-01... 67 sismos.
Descargando 2023-04-01 a 2023-05-01... 52 sismos.
Descargando 2023-05-01 a 2023-06-01... 80 sismos.
Descargando 2023-06-01 a 2023-07-01... 72 sismos.
Descargando 2023-07-01 a 2023-08-01... 71 sismos.
Descargando 2023-08-01 a 2023-09-01... 67 sismos.
Descargando 2023-09-01 a 2023-10-01... 86 sismos.
Descargando 2023-10-01 a 2023-11-01... 93 sismos.
Descargando 2023-11-01 a 2023-12-01... 79 sismos.
Descargando 2023-12-01 a 2024-01-01... 81 sismos.

¡Éxito Total! Se han descargado y unificado 3584 sismos de Chile.

In [90]:
df_japon_total = pd.read_csv("catalogo_japon_2020_2023.csv")
df_chile_total = pd.read_csv("catalogo_chile_2020_2023.csv")

In [91]:
df_japon = df_japon_total[df_japon_total["type"] == "earthquake"]
df_chile = df_chile_total[df_chile_total["type"] == "earthquake"]

In [92]:
df_japon = df_japon.dropna()
df_chile = df_chile.dropna()

In [93]:
df_japon.isnull().sum()
df_chile.isnull().sum()

time               0
latitude           0
longitude          0
depth              0
mag                0
magType            0
nst                0
gap                0
dmin               0
rms                0
net                0
id                 0
updated            0
place              0
type               0
horizontalError    0
depthError         0
magError           0
magNst             0
status             0
locationSource     0
magSource          0
dtype: int64

In [94]:
df_japon['magType'] = df_japon['magType'].astype(str).str.lower()

# 1.2 Agrupar subtipos a sus clases principales
diccionario_reemplazo = {
    'mww': 'mw', 'mwr': 'mw',  # Derivados de Magnitud de Momento
    'mlr': 'ml',               # Derivado de Magnitud Local
    'mc': 'md'                 # Coda duration -> Magnitud de Duración
}
df_japon['magType'] = df_japon['magType'].replace(diccionario_reemplazo)

df_chile['magType'] = df_chile['magType'].astype(str).str.lower()

# 1.2 Agrupar subtipos a sus clases principales
diccionario_reemplazo = {
    'mww': 'mw', 'mwr': 'mw',  # Derivados de Magnitud de Momento
    'mlr': 'ml',               # Derivado de Magnitud Local
    'mc': 'md'                 # Coda duration -> Magnitud de Duración
}
df_chile['magType'] = df_chile['magType'].replace(diccionario_reemplazo)

In [95]:
df_japon= df_japon[~df_japon['magType'].isin(["mh","ma"])]
df_japon["magType"].value_counts()

df_chile= df_chile[~df_chile['magType'].isin(["mh","ma"])]
df_chile["magType"].value_counts()

magType
mb    1049
mw     263
ml       7
Name: count, dtype: int64

In [96]:
import numpy as np
def convert_to_mw(mag, mag_type):
    if mag_type == "mw":
        return mag
    elif mag_type == "mb":
        return 1.085 * mag - 0.45
    elif mag_type == "md":
        return 1.193 * mag - 0.52
    elif mag_type == "ml":
        return 0.906 * mag + 0.02
    else:
        return np.nan

In [97]:
df_japon["mag_Mw"] = df_japon.apply(lambda row: convert_to_mw(row['mag'], row['magType']), axis=1)
df_chile["mag_Mw"] = df_chile.apply(lambda row: convert_to_mw(row['mag'], row['magType']), axis=1)

In [99]:
df_japon = df_japon.drop(columns=['mag'])
df_chile = df_chile.drop(columns=['mag'])

In [101]:
df_japon['energia_julios'] = 10 ** (1.44 * df_japon['mag_Mw'] + 5.24)
df_chile['energia_julios'] = 10 ** (1.44 * df_chile['mag_Mw'] + 5.24)

In [102]:
# ==========================================
# 1. CREACIÓN DE LA CUADRÍCULA ESPACIAL (GRID)
# ==========================================
# Redondeamos lat/lon para crear celdas (Ej: 1 grado x 1 grado)
df_japon['lat_bin'] = df_japon['latitude'].round(0)
df_japon['lon_bin'] = df_japon['longitude'].round(0)
df_japon['cell_id'] = df_japon['lat_bin'].astype(str) + "_" + df_japon['lon_bin'].astype(str)
df_japon["cell_id"].value_counts()

df_chile['lat_bin'] = df_chile['latitude'].round(0)
df_chile['lon_bin'] = df_chile['longitude'].round(0)
df_chile['cell_id'] = df_chile['lat_bin'].astype(str) + "_" + df_chile['lon_bin'].astype(str)
df_chile["cell_id"].value_counts()

cell_id
-24.0_-67.0    173
-22.0_-69.0     69
-21.0_-69.0     68
-20.0_-69.0     55
-18.0_-70.0     32
              ...
-50.0_-73.0      1
-34.0_-69.0      1
-37.0_-71.0      1
-53.0_-76.0      1
-32.0_-66.0      1
Name: count, Length: 155, dtype: int64

In [103]:
df_japon['time'] = pd.to_datetime(df_japon['time'])
df_japon['date'] = df_japon['time'].dt.floor('D')
df_chile['time'] = pd.to_datetime(df_chile['time'])
df_chile['date'] = df_chile['time'].dt.floor('D')

In [104]:
# 1. Calculamos las estadísticas generales (como ya hacías)
daily_stats_japon = df_japon.groupby(['cell_id', 'date']).agg(
    eq_count=('mag_Mw', 'count'),
    energia_acumulada_diaria=('energia_julios', 'sum')
).reset_index()

# 2. Identificamos la fila del sismo más fuerte para cada celda y día
idx_max = df_japon.groupby(['cell_id', 'date'])['mag_Mw'].idxmax()
main_events = df_japon.loc[idx_max].copy()

# 3. Renombramos las columnas del sismo principal para no confundirlas
# Por ejemplo: 'depth' pasa a ser 'main_depth'
main_events = main_events.rename(columns={
    'mag_Mw': 'main_mag',
    'depth': 'main_depth',
    'latitude': 'main_lat',
    'longitude': 'main_lon'
})

# 4. Unimos todo en un solo DataFrame de "Panel"
# Ahora cada día tiene: cuántos sismos hubo Y los detalles del sismo más fuerte
final_daily_japon = pd.merge(
    daily_stats_japon, 
    main_events[['cell_id', 'date', 'main_mag', 'main_depth', 'main_lat', 'main_lon',
                 'magError', 'depthError', 'horizontalError', 'nst', 'gap', 'dmin', 'rms', 'magNst'
                 , 'lat_bin', 'lon_bin', 'locationSource', 'magSource',
                 'net', 'status', 'updated']], 
    on=['cell_id', 'date'], 
    how='left'
)

# 1. Calculamos las estadísticas generales para Chile
daily_stats_chile = df_chile.groupby(['cell_id', 'date']).agg(
    eq_count=('mag_Mw', 'count'),
    energia_acumulada_diaria=('energia_julios', 'sum')
).reset_index()
# 2. Identificamos la fila del sismo más fuerte para cada celda y día
idx_max = df_chile.groupby(['cell_id', 'date'])['mag_Mw'].idxmax()
main_events = df_chile.loc[idx_max].copy()

# 3. Renombramos las columnas del sismo principal para no confundirlas
idx_max = df_chile.groupby(['cell_id', 'date'])['mag_Mw'].idxmax()
idx_max = (
    df_chile.dropna(subset=['mag_Mw'])
    .groupby(['cell_id', 'date'])['mag_Mw']
    .idxmax()
    .dropna()
    .astype(int)
)

main_events = df_chile.loc[idx_max].copy()

# 3. Renombramos las columnas del sismo principal para no confundirlas
# Por ejemplo: 'depth' pasa a ser 'main_depth'
main_events = main_events.rename(columns={
    'mag_Mw': 'main_mag',
    'depth': 'main_depth',
    'latitude': 'main_lat',
    'longitude': 'main_lon'
})

# 4. Unimos todo en un solo DataFrame de "Panel"
# Ahora cada día tiene: cuántos sismos hubo Y los detalles del sismo más fuerte
final_daily_chile = pd.merge(
    daily_stats_chile, 
    main_events[['cell_id', 'date', 'main_mag', 'main_depth', 'main_lat', 'main_lon',
                 'magError', 'depthError', 'horizontalError', 'nst', 'gap', 'dmin', 'rms', 'magNst'
                 , 'lat_bin', 'lon_bin', 'locationSource', 'magSource',
                 'net', 'status', 'updated']], 
    on=['cell_id', 'date'], 
    how='left'
)

In [105]:
final_daily_japon['date'] = pd.to_datetime(final_daily_japon['date']).dt.date
final_daily_chile['date'] = pd.to_datetime(final_daily_chile['date']).dt.date

In [106]:
# ==========================================
# 4. RELLENAR LOS DÍAS VACÍOS (ZEROS)
# ==========================================
# Creamos un MultiIndex con todas las combinaciones posibles de Fechas y Celdas
all_dates = pd.date_range(start=daily_stats_japon['date'].min(), end=daily_stats_japon['date'].max(), freq='D')
all_dates = pd.to_datetime(all_dates).date
all_cells = daily_stats_japon['cell_id'].unique()
full_index = pd.MultiIndex.from_product([all_cells, all_dates], names=['cell_id', 'date'])

# Reindexamos y rellenamos los nulos (días sin sismos) con ceros
panel_df_japon = final_daily_japon.set_index(['cell_id', 'date']).reindex(full_index).reset_index()

all_dates = pd.date_range(start=daily_stats_chile['date'].min(), end=daily_stats_chile['date'].max(), freq='D')
all_dates = pd.to_datetime(all_dates).date
all_cells = daily_stats_chile['cell_id'].unique()
full_index = pd.MultiIndex.from_product([all_cells, all_dates], names=['cell_id', 'date'])

panel_df_chile = final_daily_chile.set_index(['cell_id', 'date']).reindex(full_index).reset_index()

In [107]:
panel_df_japon = panel_df_japon.sort_values(['cell_id', 'date'])
panel_df_chile = panel_df_chile.sort_values(['cell_id', 'date'])

In [108]:
panel_df_japon.head(20)

,cell_id,date,eq_count,energia_acumulada_diaria,main_mag,main_depth,main_lat,main_lon,magError,depthError,...,dmin,rms,magNst,lat_bin,lon_bin,locationSource,magSource,net,status,updated
0,24.0_122.0,2022-04-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24.0_122.0,2022-04-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24.0_122.0,2022-04-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,24.0_122.0,2022-04-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24.0_122.0,2022-04-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,24.0_122.0,2022-04-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,24.0_122.0,2022-04-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,24.0_122.0,2022-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,24.0_122.0,2022-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,24.0_122.0,2022-05-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,24.0_122.0,2022-05-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,24.0_122.0,2022-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,24.0_122.0,2022-05-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,24.0_122.0,2022-05-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,24.0_122.0,2022-05-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,24.0_122.0,2022-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,24.0_122.0,2022-05-09,1.0,1.472313e+14,6.2,21.0,24.0406,122.4888,0.049,1.8,...,0.638,0.34,40.0,24.0,122.0,us,us,us,reviewed,2022-07-22T18:31:08.040Z
17,24.0_122.0,2022-05-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,24.0_122.0,2022-05-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,24.0_122.0,2022-05-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
columnas_cero = ['eq_count', 'main_mag', 'main_depth', 'main_lat', 'main_lon',
                 'magError', 'depthError', 'horizontalError', 'nst', 'gap',
                    'dmin', 'rms', 'magNst' ,'lat_bin', 'lon_bin']
panel_df_japon[columnas_cero] = panel_df_japon[columnas_cero].fillna(0)

panel_df_japon["locationSource"] = panel_df_japon["locationSource"].fillna("empty")
panel_df_japon["magSource"] = panel_df_japon["magSource"].fillna("empty")
panel_df_japon["net"] = panel_df_japon["net"].fillna("empty")
panel_df_japon["status"] = panel_df_japon["status"].fillna("empty")
panel_df_japon["updated"] = panel_df_japon["updated"].fillna("empty")
panel_df_japon['energia_acumulada_diaria'] = panel_df_japon['energia_acumulada_diaria'].fillna(0)
panel_df_japon.isnull().sum()

panel_df_chile[columnas_cero] = panel_df_chile[columnas_cero].fillna(0)

panel_df_chile["locationSource"] = panel_df_chile["locationSource"].fillna("empty")
panel_df_chile["magSource"] = panel_df_chile["magSource"].fillna("empty")
panel_df_chile["net"] = panel_df_chile["net"].fillna("empty")
panel_df_chile["status"] = panel_df_chile["status"].fillna("empty")
panel_df_chile["updated"] = panel_df_chile["updated"].fillna("empty")
panel_df_chile['energia_acumulada_diaria'] = panel_df_chile['energia_acumulada_diaria'].fillna(0)
panel_df_chile.isnull().sum()

cell_id                     0
date                        0
eq_count                    0
energia_acumulada_diaria    0
main_mag                    0
main_depth                  0
main_lat                    0
main_lon                    0
magError                    0
depthError                  0
horizontalError             0
nst                         0
gap                         0
dmin                        0
rms                         0
magNst                      0
lat_bin                     0
lon_bin                     0
locationSource              0
magSource                   0
net                         0
status                      0
updated                     0
dtype: int64

In [113]:
panel_df_japon = panel_df_japon.sort_values(['cell_id', 'date'])
panel_df_chile = panel_df_chile.sort_values(['cell_id', 'date'])

In [114]:
grouped_japon = panel_df_japon.groupby('cell_id')

# Lags directos (Día anterior t-1)
panel_df_japon['lag1_mag_max'] = grouped_japon['main_mag'].shift(1)
panel_df_japon['lag1_eq_count'] = grouped_japon['eq_count'].shift(1)
panel_df_japon['energia_lag1'] = grouped_japon['energia_acumulada_diaria'].shift(1)

# Ventanas Móviles (Rolling Windows) de los últimos 7 y 30 días (sin contar el día actual para no hacer Data Leakage)
# Usamos shift(1) para que la ventana evalúe HASTA ayer.
panel_df_japon['roll7_eq_count'] = grouped_japon['eq_count'].transform(lambda x: x.shift(1).rolling(7).sum())
panel_df_japon['roll30_eq_count'] = grouped_japon['eq_count'].transform(lambda x: x.shift(1).rolling(30).sum())
panel_df_japon['roll7_mag_max'] = grouped_japon['main_mag'].transform(lambda x: x.shift(1).rolling(7).max())
panel_df_japon['roll30_mag_max'] = grouped_japon['main_mag'].transform(lambda x: x.shift(1).rolling(30).max())
panel_df_japon['roll7_energia'] = grouped_japon['energia_acumulada_diaria'].transform(lambda x: x.shift(1).rolling(7).sum())
panel_df_japon['roll30_energia'] = grouped_japon['energia_acumulada_diaria'].transform(lambda x: x.shift(1).rolling(30).sum())

grouped_chile = panel_df_chile.groupby('cell_id')

panel_df_chile['lag1_mag_max'] = grouped_chile['main_mag'].shift(1)
panel_df_chile['lag1_eq_count'] = grouped_chile['eq_count'].shift(1)
panel_df_chile['energia_lag1'] = grouped_chile['energia_acumulada_diaria'].shift(1)

panel_df_chile['roll7_eq_count'] = grouped_chile['eq_count'].transform(lambda x: x.shift(1).rolling(7).sum())
panel_df_chile['roll30_eq_count'] = grouped_chile['eq_count'].transform(lambda x: x.shift(1).rolling(30).sum())
panel_df_chile['roll7_mag_max'] = grouped_chile['main_mag'].transform(lambda x: x.shift(1).rolling(7).max())
panel_df_chile['roll30_mag_max'] = grouped_chile['main_mag'].transform(lambda x: x.shift(1).rolling(30).max())
panel_df_chile['roll7_energia'] = grouped_chile['energia_acumulada_diaria'].transform(lambda x: x.shift(1).rolling(7).sum())
panel_df_chile['roll30_energia'] = grouped_chile['energia_acumulada_diaria'].transform(lambda x: x.shift(1).rolling(30).sum())

In [115]:
panel_df_japon['date'] = pd.to_datetime(panel_df_japon['date'])

# 2. Creamos la columna temporal con las fechas de sismos
panel_df_japon['temp_eq_date'] = panel_df_japon['date'].where(panel_df_japon['eq_count'] > 0)
# 3. EL TRUCO: Aplicamos ffill() y shift() DENTRO del groupby
panel_df_japon['last_eq_date'] = panel_df_japon.groupby('cell_id')['temp_eq_date'].transform(lambda x: x.ffill().shift(1))
panel_df_japon['days_since_last_eq'] = (panel_df_japon['date'] - panel_df_japon['last_eq_date']).dt.days  #.fillna(999).astype(int)


panel_df_chile['date'] = pd.to_datetime(panel_df_chile['date'])

panel_df_chile['temp_eq_date'] = panel_df_chile['date'].where(panel_df_chile['eq_count'] > 0)

panel_df_chile['last_eq_date'] = panel_df_chile.groupby('cell_id')['temp_eq_date'].transform(lambda x: x.ffill().shift(1))
panel_df_chile['days_since_last_eq'] = (panel_df_chile['date'] - panel_df_chile['last_eq_date']).dt.days  #.fillna(999).astype(int)

In [116]:
panel_df_japon["days_since_last_eq"].describe()

count    93421.000000
mean        99.643367
std        106.917315
min          1.000000
25%         22.000000
50%         61.000000
75%        138.000000
max        616.000000
Name: days_since_last_eq, dtype: float64

In [117]:
panel_df_japon['main_mag'].describe()

count    126690.000000
mean          0.054628
std           0.491347
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           6.300000
Name: main_mag, dtype: float64

In [118]:
panel_df_japon['TARGET_mag_max_next_7d'] = grouped_japon['main_mag'].transform(lambda x: x.rolling(7).max().shift(-7))

# Target Clasificación: ¿Habrá un sismo mayor a 4.5 en los próximos 7 días?
panel_df_japon['TARGET_occurrence_M4.5'] = (panel_df_japon['TARGET_mag_max_next_7d'] >= 4.5).astype(int)
panel_df_japon['TARGET_occurrence_M3.0'] = (panel_df_japon['TARGET_mag_max_next_7d'] >= 3.0).astype(int)

panel_df_chile['TARGET_mag_max_next_7d'] = grouped_chile['main_mag'].transform(lambda x: x.rolling(7).max().shift(-7))

panel_df_chile['TARGET_occurrence_M4.5'] = (panel_df_chile['TARGET_mag_max_next_7d'] >= 4.5).astype(int)
panel_df_chile['TARGET_occurrence_M3.0'] = (panel_df_chile['TARGET_mag_max_next_7d'] >= 3.0).astype(int)

In [119]:
panel_df_japon.describe()

,date,eq_count,energia_acumulada_diaria,main_mag,main_depth,main_lat,main_lon,magError,depthError,horizontalError,...,roll7_mag_max,roll30_mag_max,roll7_energia,roll30_energia,temp_eq_date,last_eq_date,days_since_last_eq,TARGET_mag_max_next_7d,TARGET_occurrence_M4.5,TARGET_occurrence_M3.0
count,126690,126690.000000,1.266900e+05,126690.000000,126690.000000,126690.000000,126690.000000,126690.000000,126690.000000,126690.000000,...,125255.000000,120540.000000,1.252550e+05,1.205400e+05,1560,93421,93421.000000,125255.000000,126690.000000,126690.000000
mean,2023-02-25 12:00:00,0.016323,3.490123e+10,0.054628,0.967255,0.411689,1.702872,0.001394,0.058527,0.091441,...,0.324449,1.072903,2.462647e+11,1.062603e+12,2023-02-21 10:21:13.846153472,2023-01-10 00:16:50.856231424,99.643367,0.324276,0.025385,0.072066
min,2022-04-23 00:00:00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,2022-04-23 00:00:00,2022-04-23 00:00:00,1.000000,0.000000,0.000000,0.000000
25%,2022-09-24 00:00:00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,2022-09-13 00:00:00,2022-08-24 00:00:00,22.000000,0.000000,0.000000,0.000000
50%,2023-02-25 12:00:00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,2023-02-22 00:00:00,2022-12-27 00:00:00,61.000000,0.000000,0.000000,0.000000
75%,2023-07-30 00:00:00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,2023-08-07 06:00:00,2023-05-21 00:00:00,138.000000,0.000000,0.000000,0.000000
max,2023-12-31 00:00:00,40.000000,2.215807e+14,6.300000,644.879000,45.980400,145.973600,0.309000,13.620000,15.860000,...,6.300000,6.300000,6.154979e+14,6.173232e+14,2023-12-31 00:00:00,2023-12-30 00:00:00,616.000000,6.300000,1.000000,1.000000
std,NaN,0.246793,1.639864e+12,0.491347,15.224698,3.740391,15.266364,0.014004,0.597808,0.853571,...,1.162211,1.926118,5.567241e+12,1.242726e+13,NaN,NaN,106.917315,1.161998,0.157291,0.258598

In [120]:
df_j = panel_df_japon.copy()
df_ch = panel_df_chile.copy()

In [121]:
df_j[['lat', 'lon']] = df_j['cell_id'].str.split('_', expand=True).astype(float)

df_ch[['lat', 'lon']] = df_ch['cell_id'].str.split('_', expand=True).astype(float)

In [122]:
offsets = [
    (-1, -1), (-1, 0), (-1, 1), # Sur-Oeste, Sur, Sur-Este
    ( 0, -1),          ( 0, 1), # Oeste,          Este
    ( 1, -1), ( 1, 0), ( 1, 1)  # Nor-Oeste, Norte, Nor-Este
]

shifted_dfs = []

# Nombres de tus columnas originales (CÁMBIALOS SI SE LLAMAN DISTINTO EN TU DF)
col_fecha = 'date'
col_n_sismos = 'eq_count'
col_mag = 'main_mag'
col_roll7_eq_count = 'roll7_eq_count'
col_roll7_mag_max = 'roll7_mag_max'
col_roll7_energia = 'roll7_energia'
col_roll30_energia = 'roll30_energia'
col_roll30_eq_count = 'roll30_eq_count'
col_roll30_mag_max = 'roll30_mag_max'

for d_lat, d_lon in offsets:
    # Hacemos una copia solo de las columnas necesarias
    df_neighbor_j = df_j[[col_fecha, 'lat', 'lon', col_n_sismos, col_mag, col_roll7_eq_count, col_roll7_mag_max, col_roll30_energia, col_roll30_eq_count, col_roll30_mag_max]].copy()
    
    # TRUCO MÁGICO: "Movemos" las coordenadas de esta celda hacia su vecina.
    # Al restar el offset, los datos de la celda vecina caerán matemáticamente
    # encima de las coordenadas de nuestra celda objetivo.
    df_neighbor_j['lat'] = df_neighbor_j['lat'] - d_lat
    df_neighbor_j['lon'] = df_neighbor_j['lon'] - d_lon
    
    # Renombrar para saber que son datos del vecino
    df_neighbor_j = df_neighbor_j.rename(columns={
        col_n_sismos: 'neigh_num_eqs',
        col_mag: 'neigh_mag',
        col_roll7_eq_count: 'neigh_roll7_eq_count',
        col_roll7_mag_max: 'neigh_roll7_mag_max',
        col_roll30_energia: 'neigh_roll30_energia',
        col_roll30_eq_count: 'neigh_roll30_eq_count',
        col_roll30_mag_max: 'neigh_roll30_mag_max'
    })
    
    shifted_dfs.append(df_neighbor_j)

all_neighbors = pd.concat(shifted_dfs, ignore_index=True)

# 5. Agrupar por Fecha, Latitud y Longitud objetivo para calcular el total de los 8 vecinos
vecinos_agrupados = all_neighbors.groupby([col_fecha, 'lat', 'lon']).agg(
    adj_num_eqs=('neigh_num_eqs', 'sum'), # SUMAR la cantidad de terremotos de los vecinos
    adj_max_mag=('neigh_mag', 'max'),     # Extraer la MAGNITUD MÁXIMA de los vecinos
    adj_roll7_eq_count=('neigh_roll7_eq_count', 'sum'), # SUMAR la cantidad de terremotos de los vecinos (ventana 7 días)
    adj_roll7_mag_max=('neigh_roll7_mag_max', 'max'),      # Extraer la MAGNITUD MÁXIMA de los vecinos (ventana 7 días)
    adj_roll30_energia=('neigh_roll30_energia', 'sum'), # SUMAR la cantidad de terremotos de los vecinos (ventana 30 días)
    adj_roll30_eq_count=('neigh_roll30_eq_count', 'sum'), # SUMAR la cantidad de terremotos de los vecinos (ventana 30 días)
    adj_roll30_mag_max=('neigh_roll30_mag_max', 'max')      # Extraer la MAGNITUD MÁXIMA de los vecinos (ventana 30 días)

).reset_index()

# 6. Unimos estas nuevas variables de vuelta a nuestro DataFrame original
df_j = df_j.merge(
    vecinos_agrupados, 
    on=[col_fecha, 'lat', 'lon'], 
    how='left'
)

In [123]:
offsets = [
    (-1, -1), (-1, 0), (-1, 1), # Sur-Oeste, Sur, Sur-Este
    ( 0, -1),          ( 0, 1), # Oeste,          Este
    ( 1, -1), ( 1, 0), ( 1, 1)  # Nor-Oeste, Norte, Nor-Este
]

shifted_dfs = []

# Nombres de tus columnas originales (CÁMBIALOS SI SE LLAMAN DISTINTO EN TU DF)
col_fecha = 'date'
col_n_sismos = 'eq_count'
col_mag = 'main_mag'
col_roll7_eq_count = 'roll7_eq_count'
col_roll7_mag_max = 'roll7_mag_max'
col_roll7_energia = 'roll7_energia'
col_roll30_energia = 'roll30_energia'
col_roll30_eq_count = 'roll30_eq_count'
col_roll30_mag_max = 'roll30_mag_max'

for d_lat, d_lon in offsets:
    # Hacemos una copia solo de las columnas necesarias
    df_neighbor = df_ch[[col_fecha, 'lat', 'lon', col_n_sismos, col_mag, col_roll7_eq_count, col_roll7_mag_max, col_roll30_energia, col_roll30_eq_count, col_roll30_mag_max]].copy()
    
    # TRUCO MÁGICO: "Movemos" las coordenadas de esta celda hacia su vecina.
    # Al restar el offset, los datos de la celda vecina caerán matemáticamente
    # encima de las coordenadas de nuestra celda objetivo.
    df_neighbor['lat'] = df_neighbor['lat'] - d_lat
    df_neighbor['lon'] = df_neighbor['lon'] - d_lon
    
    # Renombrar para saber que son datos del vecino
    df_neighbor = df_neighbor.rename(columns={
        col_n_sismos: 'neigh_num_eqs',
        col_mag: 'neigh_mag',
        col_roll7_eq_count: 'neigh_roll7_eq_count',
        col_roll7_mag_max: 'neigh_roll7_mag_max',
        col_roll30_energia: 'neigh_roll30_energia',
        col_roll30_eq_count: 'neigh_roll30_eq_count',
        col_roll30_mag_max: 'neigh_roll30_mag_max'
    })
    
    shifted_dfs.append(df_neighbor)

all_neighbors = pd.concat(shifted_dfs, ignore_index=True)

# 5. Agrupar por Fecha, Latitud y Longitud objetivo para calcular el total de los 8 vecinos
vecinos_agrupados = all_neighbors.groupby([col_fecha, 'lat', 'lon']).agg(
    adj_num_eqs=('neigh_num_eqs', 'sum'), # SUMAR la cantidad de terremotos de los vecinos
    adj_max_mag=('neigh_mag', 'max'),     # Extraer la MAGNITUD MÁXIMA de los vecinos
    adj_roll7_eq_count=('neigh_roll7_eq_count', 'sum'), # SUMAR la cantidad de terremotos de los vecinos (ventana 7 días)
    adj_roll7_mag_max=('neigh_roll7_mag_max', 'max'),      # Extraer la MAGNITUD MÁXIMA de los vecinos (ventana 7 días)
    adj_roll30_energia=('neigh_roll30_energia', 'sum'), # SUMAR la cantidad de terremotos de los vecinos (ventana 30 días)
    adj_roll30_eq_count=('neigh_roll30_eq_count', 'sum'), # SUMAR la cantidad de terremotos de los vecinos (ventana 30 días)
    adj_roll30_mag_max=('neigh_roll30_mag_max', 'max')      # Extraer la MAGNITUD MÁXIMA de los vecinos (ventana 30 días)

).reset_index()

# 6. Unimos estas nuevas variables de vuelta a nuestro DataFrame original
df_ch = df_ch.merge(
    vecinos_agrupados, 
    on=[col_fecha, 'lat', 'lon'], 
    how='left'
)

Prueba de cla

In [124]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df = df_j.copy() # as.data.frame no es estrictamente necesario, pandas ya usa DataFrames

# 2. Suavizar con logaritmo la energía
# np.log1p(x) es el equivalente exacto y optimizado matemáticamente para log(x + 1)
cols_log = [
    'energia_acumulada_diaria', 'energia_lag1', 
    'roll7_energia', 'roll30_energia', 'adj_roll30_energia'
]
df[cols_log] = np.log1p(df[cols_log])

# 3. Estandarización de las variables numéricas
listconti = [
    "eq_count", "energia_acumulada_diaria", "main_mag", "main_depth", "main_lat", 
    "main_lon", "magError", "depthError", "horizontalError", "nst", "gap", "dmin", 
    "rms", "magNst",  "lat_bin", "lon_bin", 
    "lag1_mag_max", "lag1_eq_count", "energia_lag1", "roll7_eq_count", "roll30_eq_count", 
    "roll7_mag_max", "roll30_mag_max", "roll7_energia", "roll30_energia", 
    "days_since_last_eq", "TARGET_mag_max_next_7d", "lat", "lon", 
      "adj_roll7_eq_count", 
    "adj_roll7_mag_max", "adj_roll30_energia", "adj_roll30_eq_count", "adj_roll30_mag_max"
]

scaler = StandardScaler()
df[listconti] = scaler.fit_transform(df[listconti])

# 4. Convertir lógicas a numéricas
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)


# Asegurar que la columna 'date' es de tipo datetime para permitir cortes temporales
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

test_j  = df.copy()


# 6. Target encoding con ventana móvil
# Creamos una función para evitar repetir el código 4 veces.
def apply_rolling_target_encoding(data, target_col, new_col_name):
    """
    Replica el comportamiento de slide_index_dbl(..., .before=days(30), .after=-1)
    """
    # Guardar la media global para el llenado de NAs
    global_mean = data[target_col].mean()
    
    # 1. Ordenar explícitamente es necesario para funciones rolling indexadas
    data = data.sort_values(by=['cell_id', 'date'])
    
    # 2. Configurar la fecha como índice temporal para que funcione el '30D'
    data_idx = data.set_index('date')
    
    # 3. Agrupar y aplicar la ventana móvil.
    # closed='left' es la clave: calcula usando datos hasta el día de ayer, excluyendo hoy (-1)
    rolling_means = (
        data_idx.groupby('cell_id')[target_col]
        .rolling('30D', closed='left')
        .mean()
    )
    
    # 4. Extraer los valores calculados a la columna nueva
    data[new_col_name] = rolling_means.values
    
    # 5. Rellenar NAs iniciales con la media global
    data[new_col_name] = data[new_col_name].fillna(global_mean)
    
    return data

# Aplicación en los conjuntos
# Nota: En tu script de R creabas dataframes paralelos (train_enc_cla, train_enc_cla2). 
# Aquí los agrego al mismo dataframe (train y test) porque es más seguro evitar bifurcar 
# los datos con variables separadas, manteniendo todo consolidado.

# Prueba
test_j = apply_rolling_target_encoding(test_j, 'TARGET_occurrence_M3.0', 'target_cla_enc_30d')
test_j = apply_rolling_target_encoding(test_j, 'TARGET_occurrence_M4.5', 'target_cla_enc_30d2')

datetime64[ns]

In [125]:
df = df_ch.copy() # as.data.frame no es estrictamente necesario, pandas ya usa DataFrames

# 2. Suavizar con logaritmo la energía
# np.log1p(x) es el equivalente exacto y optimizado matemáticamente para log(x + 1)
cols_log = [
    'energia_acumulada_diaria', 'energia_lag1', 
    'roll7_energia', 'roll30_energia', 'adj_roll30_energia'
]
df[cols_log] = np.log1p(df[cols_log])

# 3. Estandarización de las variables numéricas
listconti = [
    "eq_count", "energia_acumulada_diaria", "main_mag", "main_depth", "main_lat", 
    "main_lon", "magError", "depthError", "horizontalError", "nst", "gap", "dmin", 
    "rms", "magNst",  "lat_bin", "lon_bin", 
    "lag1_mag_max", "lag1_eq_count", "energia_lag1", "roll7_eq_count", "roll30_eq_count", 
    "roll7_mag_max", "roll30_mag_max", "roll7_energia", "roll30_energia", 
    "days_since_last_eq", "TARGET_mag_max_next_7d", "lat", "lon", 
      "adj_roll7_eq_count", 
    "adj_roll7_mag_max", "adj_roll30_energia", "adj_roll30_eq_count", "adj_roll30_mag_max"
]

scaler = StandardScaler()
df[listconti] = scaler.fit_transform(df[listconti])

# 4. Convertir lógicas a numéricas
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)


# Asegurar que la columna 'date' es de tipo datetime para permitir cortes temporales
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

test_ch = df.copy()


# 6. Target encoding con ventana móvil
# Creamos una función para evitar repetir el código 4 veces.
def apply_rolling_target_encoding(data, target_col, new_col_name):
    """
    Replica el comportamiento de slide_index_dbl(..., .before=days(30), .after=-1)
    """
    # Guardar la media global para el llenado de NAs
    global_mean = data[target_col].mean()
    
    # 1. Ordenar explícitamente es necesario para funciones rolling indexadas
    data = data.sort_values(by=['cell_id', 'date'])
    
    # 2. Configurar la fecha como índice temporal para que funcione el '30D'
    data_idx = data.set_index('date')
    
    # 3. Agrupar y aplicar la ventana móvil.
    # closed='left' es la clave: calcula usando datos hasta el día de ayer, excluyendo hoy (-1)
    rolling_means = (
        data_idx.groupby('cell_id')[target_col]
        .rolling('30D', closed='left')
        .mean()
    )
    
    # 4. Extraer los valores calculados a la columna nueva
    data[new_col_name] = rolling_means.values
    
    # 5. Rellenar NAs iniciales con la media global
    data[new_col_name] = data[new_col_name].fillna(global_mean)
    
    return data

# Aplicación en los conjuntos
# Nota: En tu script de R creabas dataframes paralelos (train_enc_cla, train_enc_cla2). 
# Aquí los agrego al mismo dataframe (train y test) porque es más seguro evitar bifurcar 
# los datos con variables separadas, manteniendo todo consolidado.

# Prueba
test_ch = apply_rolling_target_encoding(test_ch, 'TARGET_occurrence_M3.0', 'target_cla_enc_30d')
test_ch = apply_rolling_target_encoding(test_ch, 'TARGET_occurrence_M4.5', 'target_cla_enc_30d2')

datetime64[ns]

In [44]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# 1. Lectura de datos
datos = pd.read_csv("datos_mw_conv_final_ohe.csv")
df = datos.copy() # as.data.frame no es estrictamente necesario, pandas ya usa DataFrames

# 2. Suavizar con logaritmo la energía
# np.log1p(x) es el equivalente exacto y optimizado matemáticamente para log(x + 1)
cols_log = [
    'energia_acumulada_diaria', 'energia_lag1', 
    'roll7_energia', 'roll30_energia', 'adj_roll30_energia'
]
df[cols_log] = np.log1p(df[cols_log])

# 3. Estandarización de las variables numéricas
listconti = [
    "eq_count", "energia_acumulada_diaria", "main_mag", "main_depth", "main_lat", 
    "main_lon", "magError", "depthError", "horizontalError", "nst", "gap", "dmin", 
    "rms", "magNst", "is_converted_mag", "lat_bin", "lon_bin", "b_value_daily", 
    "lag1_mag_max", "lag1_eq_count", "energia_lag1", "roll7_eq_count", "roll30_eq_count", 
    "roll7_mag_max", "roll30_mag_max", "roll7_energia", "roll30_energia", 
    "days_since_last_eq", "TARGET_mag_max_next_7d", "lat", "lon", "adj_num_eqs_x", 
    "adj_max_mag_x", "adj_num_eqs_y", "adj_max_mag_y", "adj_roll7_eq_count", 
    "adj_roll7_mag_max", "adj_roll30_energia", "adj_roll30_eq_count", "adj_roll30_mag_max"
]

scaler = StandardScaler()
df[listconti] = scaler.fit_transform(df[listconti])

# 4. Convertir lógicas a numéricas
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)


# Asegurar que la columna 'date' es de tipo datetime para permitir cortes temporales
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

# 5. División en train y test por corte de tiempo
train = df[df['date'] < "2019-01-01"].copy()
test  = df[df['date'] >= "2019-01-01"].copy()


# 6. Target encoding con ventana móvil
# Creamos una función para evitar repetir el código 4 veces.
def apply_rolling_target_encoding(data, target_col, new_col_name):
    """
    Replica el comportamiento de slide_index_dbl(..., .before=days(30), .after=-1)
    """
    # Guardar la media global para el llenado de NAs
    global_mean = data[target_col].mean()
    
    # 1. Ordenar explícitamente es necesario para funciones rolling indexadas
    data = data.sort_values(by=['cell_id', 'date'])
    
    # 2. Configurar la fecha como índice temporal para que funcione el '30D'
    data_idx = data.set_index('date')
    
    # 3. Agrupar y aplicar la ventana móvil.
    # closed='left' es la clave: calcula usando datos hasta el día de ayer, excluyendo hoy (-1)
    rolling_means = (
        data_idx.groupby('cell_id')[target_col]
        .rolling('30D', closed='left')
        .mean()
    )
    
    # 4. Extraer los valores calculados a la columna nueva
    data[new_col_name] = rolling_means.values
    
    # 5. Rellenar NAs iniciales con la media global
    data[new_col_name] = data[new_col_name].fillna(global_mean)
    
    return data

# Aplicación en los conjuntos
# Nota: En tu script de R creabas dataframes paralelos (train_enc_cla, train_enc_cla2). 
# Aquí los agrego al mismo dataframe (train y test) porque es más seguro evitar bifurcar 
# los datos con variables separadas, manteniendo todo consolidado.

# Entrenamiento
train = apply_rolling_target_encoding(train, 'TARGET_occurrence_M3.0', 'target_cla_enc_30d')
train = apply_rolling_target_encoding(train, 'TARGET_occurrence_M4.5', 'target_cla_enc_30d2')

# Prueba
test = apply_rolling_target_encoding(test, 'TARGET_occurrence_M3.0', 'target_cla_enc_30d')
test = apply_rolling_target_encoding(test, 'TARGET_occurrence_M4.5', 'target_cla_enc_30d2')

datetime64[ns]

In [45]:
listconti2 = ["target_cla_enc_30d", "days_since_last_eq", "adj_roll30_energia", 
              "roll30_energia", "roll30_mag_max", "lon", "eq_count", "lat", 
              "lag1_eq_count"]

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import classification_report, confusion_matrix
X_train = train[listconti2]
y_train = train["TARGET_occurrence_M3.0"]  # o TARGET_occurrence_M4.5 según el objetivo

X_test = test[listconti2]
y_test = test["TARGET_occurrence_M3.0"] 
 
# ============================================
# CONFIGURACIÓN COMPLETA EQUIVALENTE A SAS
# ============================================
rf_sas_config = RandomForestClassifier(
    # === OPCIONES DE ÁRBOL ===
    n_estimators=100,           # Número máximo de árboles
    random_state=12345,         # Semilla para reproducibilidad
    
    # === OPCIONES DE MUESTRA ===
    bootstrap=True,             # Muestreo con reemplazo (tipo muestra)
    max_samples=0.6,            # Proporción de observación (60%)
    # Nota: En SAS "Proporción de observación" es similar a sampling rate
    
    # === OPCIONES DE REGLA/DIVISIÓN ===
    max_depth=50,               # Profundidad máxima del árbol
    max_features='sqrt',        # Número de variables a considerar
    # 'sqrt' = raíz cuadrada del total de variables (común en SAS)
    
    min_samples_split=2,        # Tamaño mínimo del nodo para dividir
    # Nota: "Uso mínimo en Profundidad máxima" refiere a esto
    
    # === OPCIONES DE NODO ===
    min_samples_leaf=1,         # Tamaño mínimo del nodo hijo
    min_impurity_decrease=1e-5, # Porcentaje más del 1.0E-5 (usando el valor exacto)
    
    # === OTRAS OPCIONES ===
    criterion='gini',           # Medida de impurity (Gini)
    verbose=0,                  # Sin logs
    n_jobs=-1                   # Usar todos los procesadores
)

rf_sas_config.fit(X_train, y_train)

# Evaluar
y_pred = rf_sas_config.predict(X_test)
print(classification_report(y_test, y_pred))

# Importancia de características
importances = pd.DataFrame({
    'feature': listconti2,
    'importance': rf_sas_config.feature_importances_
}).sort_values('importance', ascending=False)
print(importances)

cm = confusion_matrix(y_test, y_pred)
print(cm)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99    185490
           1       0.96      0.61      0.75      5505

    accuracy                           0.99    190995
   macro avg       0.98      0.81      0.87    190995
weighted avg       0.99      0.99      0.99    190995

              feature  importance
0  target_cla_enc_30d    0.606436
4      roll30_mag_max    0.192969
3      roll30_energia    0.106336
1  days_since_last_eq    0.043323
6            eq_count    0.026179
2  adj_roll30_energia    0.007448
8       lag1_eq_count    0.007335
7                 lat    0.005258
5                 lon    0.004716
[[185367    123]
 [  2126   3379]]

In [126]:
y_pred_j = rf_sas_config.predict(test_j[listconti2])
y_pred_ch = rf_sas_config.predict(test_ch[listconti2])

In [127]:
print(classification_report(test_j["TARGET_occurrence_M3.0"], y_pred_j))
print(classification_report(test_ch["TARGET_occurrence_M3.0"], y_pred_ch))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97    117560
           1       0.70      0.54      0.61      9130

    accuracy                           0.95    126690
   macro avg       0.83      0.76      0.79    126690
weighted avg       0.95      0.95      0.95    126690

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     88577
           1       0.78      0.53      0.63      7213

    accuracy                           0.95     95790
   macro avg       0.87      0.76      0.80     95790
weighted avg       0.95      0.95      0.95     95790

In [129]:
cm_japon = confusion_matrix(test_j["TARGET_occurrence_M3.0"], y_pred_j)
cm_chile = confusion_matrix(test_ch["TARGET_occurrence_M3.0"], y_pred_ch)
cm_df_japon = pd.DataFrame(
    cm_japon,
    index=['Real: Negativo (Clase 0)', 'Real: Positivo (Clase 1)'],
    columns=['Pred: Negativo (Clase 0)', 'Pred: Positivo (Clase 1)']
)
cm_df_chile = pd.DataFrame(
    cm_chile,
    index=['Real: Negativo (Clase 0)', 'Real: Positivo (Clase 1)'],
    columns=['Pred: Negativo (Clase 0)', 'Pred: Positivo (Clase 1)']
)

print("\n📊 MATRIZ DE CONFUSIÓN (JAPÓN):")
print(cm_df_japon)
print("\n" + "="*70)
print("\n📊 MATRIZ DE CONFUSIÓN (CHILE):")
print(cm_df_chile)
print("\n" + "="*70)

# Extraer valores
tn, fp, fn, tp = cm.ravel()

print(f"""
🔍 LECTURA DETALLADA:

┌──────────────┬─────────────────┬─────────────────┐
│              │ PREDICHO NEGATIVO │ PREDICHO POSITIVO │
├──────────────┼─────────────────┼─────────────────┤
│ REAL NEGATIVO│  {tn} (TN) ✅      │  {fp} (FP) ❌      │
│              │  Correctos       │  Error Tipo I    │
├──────────────┼─────────────────┼─────────────────┤
│ REAL POSITIVO│  {fn} (FN) ❌      │  {tp} (TP) ✅      │
│              │  Error Tipo II   │  Correctos       │
└──────────────┴─────────────────┴─────────────────┘

📌 SIGNIFICADO:
• TN ({tn}): El modelo predijo CORRECTAMENTE "Negativo" cuando era Negativo
• FP ({fp}): El modelo predijo INCORRECTAMENTE "Positivo" cuando era Negativo
• FN ({fn}): El modelo predijo INCORRECTAMENTE "Negativo" cuando era Positivo  
• TP ({tp}): El modelo predijo CORRECTAMENTE "Positivo" cuando era Positivo
""")

📊 MATRIZ DE CONFUSIÓN (JAPÓN):
                          Pred: Negativo (Clase 0)  Pred: Positivo (Clase 1)
Real: Negativo (Clase 0)                    115472                      2088
Real: Positivo (Clase 1)                      4165                      4965

======================================================================

📊 MATRIZ DE CONFUSIÓN (CHILE):
                          Pred: Negativo (Clase 0)  Pred: Positivo (Clase 1)
Real: Negativo (Clase 0)                     87532                      1045
Real: Positivo (Clase 1)                      3404                      3809

======================================================================

🔍 LECTURA DETALLADA:

┌──────────────┬─────────────────┬─────────────────┐
│              │ PREDICHO NEGATIVO │ PREDICHO POSITIVO │
├──────────────┼─────────────────┼─────────────────┤
│ REAL NEGATIVO│  185367 (TN) ✅      │  123 (FP) ❌      │
│              │  Correctos       │  Error Tipo I    │
├──────────────┼─────────────────┼─────────────────┤
│ REAL POSITIVO│  2126 (FN) ❌      │  3379 (TP) ✅      │
│              │  Error Tipo II   │  Correctos       │
└──────────────┴─────────────────┴─────────────────┘

📌 SIGNIFICADO:
• TN (185367): El modelo predijo CORRECTAMENTE "Negativo" cuando era Negativo
• FP (123): El modelo predijo INCORRECTAMENTE "Positivo" cuando era Negativo
• FN (2126): El modelo predijo INCORRECTAMENTE "Negativo" cuando era Positivo
• TP (3379): El modelo predijo CORRECTAMENTE "Positivo" cuando era Positivo

Para regresión

In [131]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# 1. Lectura de datos
datos = df_j.copy()
df = datos.copy() # as.data.frame no es estrictamente necesario, pandas ya usa DataFrames

# 2. Suavizar con logaritmo la energía
# np.log1p(x) es el equivalente exacto y optimizado matemáticamente para log(x + 1)
cols_log = [
    'energia_acumulada_diaria', 'energia_lag1', 
    'roll7_energia', 'roll30_energia', 'adj_roll30_energia'
]
df[cols_log] = np.log1p(df[cols_log])

# 3. Estandarización de las variables numéricas
listconti = [
    "eq_count", "energia_acumulada_diaria", "main_mag", "main_depth", "main_lat", 
    "main_lon", "magError", "depthError", "horizontalError", "nst", "gap", "dmin", 
    "rms", "magNst",  "lat_bin", "lon_bin", 
    "lag1_mag_max", "lag1_eq_count", "energia_lag1", "roll7_eq_count", "roll30_eq_count", 
    "roll7_mag_max", "roll30_mag_max", "roll7_energia", "roll30_energia", 
    "days_since_last_eq", "TARGET_mag_max_next_7d", "lat", "lon", "adj_roll7_eq_count", 
    "adj_roll7_mag_max", "adj_roll30_energia", "adj_roll30_eq_count", "adj_roll30_mag_max"
]

scaler = StandardScaler()
df[listconti] = scaler.fit_transform(df[listconti])

# 4. Convertir lógicas a numéricas
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)


# Asegurar que la columna 'date' es de tipo datetime para permitir cortes temporales
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

test_j  = df[df['date'] >= "2019-01-01"].copy()
def compute_target_reg_enc_30d(df):
    # Hacer una copia y resetear índices
    df = df.copy().reset_index(drop=True)
    
    # Crear columna con NaN
    df['target_reg_enc_30d'] = np.nan
    
    # Procesar cada cell_id
    for cell_id in df['cell_id'].unique():
        # Obtener índices del grupo actual
        group_mask = df['cell_id'] == cell_id
        group_indices = df[group_mask].index
        
        # Si el grupo está vacío, continuar
        if len(group_indices) == 0:
            continue
        
        # Ordenar por fecha dentro del grupo
        group_df = df.loc[group_indices].sort_values('date')
        
        # Calcular rolling mean
        try:
            rolling_result = (
                group_df
                .set_index('date')['TARGET_mag_max_next_7d']
                .rolling('30D', closed='left')
                .mean()
            )
            
            # Asignar resultados
            df.loc[group_indices, 'target_reg_enc_30d'] = rolling_result.to_numpy()
            
        except Exception as e:
            print(f"Error procesando cell_id {cell_id}: {e}")
            # Fallback: usar media simple
            df.loc[group_indices, 'target_reg_enc_30d'] = (
                group_df['TARGET_mag_max_next_7d']
                .shift(1)
                .rolling(window=30, min_periods=1)
                .mean()
                .to_numpy()
            )
    
    return df

# Aplicar
test_j = compute_target_reg_enc_30d(test_j)
test_j['target_reg_enc_30d'].fillna(test_j['TARGET_mag_max_next_7d'].mean(), inplace=True)

datetime64[ns]

C:\Users\longj\AppData\Local\Temp\ipykernel_17740\2658879195.py:88: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_j['target_reg_enc_30d'].fillna(test_j['TARGET_mag_max_next_7d'].mean(), inplace=True)

In [132]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# 1. Lectura de datos
datos = df_ch.copy()
df = datos.copy() # as.data.frame no es estrictamente necesario, pandas ya usa DataFrames

# 2. Suavizar con logaritmo la energía
# np.log1p(x) es el equivalente exacto y optimizado matemáticamente para log(x + 1)
cols_log = [
    'energia_acumulada_diaria', 'energia_lag1', 
    'roll7_energia', 'roll30_energia', 'adj_roll30_energia'
]
df[cols_log] = np.log1p(df[cols_log])

# 3. Estandarización de las variables numéricas
listconti = [
    "eq_count", "energia_acumulada_diaria", "main_mag", "main_depth", "main_lat", 
    "main_lon", "magError", "depthError", "horizontalError", "nst", "gap", "dmin", 
    "rms", "magNst",  "lat_bin", "lon_bin", 
    "lag1_mag_max", "lag1_eq_count", "energia_lag1", "roll7_eq_count", "roll30_eq_count", 
    "roll7_mag_max", "roll30_mag_max", "roll7_energia", "roll30_energia", 
    "days_since_last_eq", "TARGET_mag_max_next_7d", "lat", "lon", "adj_roll7_eq_count", 
    "adj_roll7_mag_max", "adj_roll30_energia", "adj_roll30_eq_count", "adj_roll30_mag_max"
]

scaler = StandardScaler()
df[listconti] = scaler.fit_transform(df[listconti])

# 4. Convertir lógicas a numéricas
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)


# Asegurar que la columna 'date' es de tipo datetime para permitir cortes temporales
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

test_ch  = df[df['date'] >= "2019-01-01"].copy()
def compute_target_reg_enc_30d(df):
    # Hacer una copia y resetear índices
    df = df.copy().reset_index(drop=True)
    
    # Crear columna con NaN
    df['target_reg_enc_30d'] = np.nan
    
    # Procesar cada cell_id
    for cell_id in df['cell_id'].unique():
        # Obtener índices del grupo actual
        group_mask = df['cell_id'] == cell_id
        group_indices = df[group_mask].index
        
        # Si el grupo está vacío, continuar
        if len(group_indices) == 0:
            continue
        
        # Ordenar por fecha dentro del grupo
        group_df = df.loc[group_indices].sort_values('date')
        
        # Calcular rolling mean
        try:
            rolling_result = (
                group_df
                .set_index('date')['TARGET_mag_max_next_7d']
                .rolling('30D', closed='left')
                .mean()
            )
            
            # Asignar resultados
            df.loc[group_indices, 'target_reg_enc_30d'] = rolling_result.to_numpy()
            
        except Exception as e:
            print(f"Error procesando cell_id {cell_id}: {e}")
            # Fallback: usar media simple
            df.loc[group_indices, 'target_reg_enc_30d'] = (
                group_df['TARGET_mag_max_next_7d']
                .shift(1)
                .rolling(window=30, min_periods=1)
                .mean()
                .to_numpy()
            )
    
    return df

# Aplicar
test_ch = compute_target_reg_enc_30d(test_ch)
test_ch['target_reg_enc_30d'].fillna(test_ch['TARGET_mag_max_next_7d'].mean(), inplace=True)

datetime64[ns]

C:\Users\longj\AppData\Local\Temp\ipykernel_17740\641434219.py:88: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_ch['target_reg_enc_30d'].fillna(test_ch['TARGET_mag_max_next_7d'].mean(), inplace=True)

In [133]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# 1. Lectura de datos
datos = pd.read_csv("datos_mw_conv_final_ohe.csv")
df = datos.copy() # as.data.frame no es estrictamente necesario, pandas ya usa DataFrames

# 2. Suavizar con logaritmo la energía
# np.log1p(x) es el equivalente exacto y optimizado matemáticamente para log(x + 1)
cols_log = [
    'energia_acumulada_diaria', 'energia_lag1', 
    'roll7_energia', 'roll30_energia', 'adj_roll30_energia'
]
df[cols_log] = np.log1p(df[cols_log])

# 3. Estandarización de las variables numéricas
listconti = [
    "eq_count", "energia_acumulada_diaria", "main_mag", "main_depth", "main_lat", 
    "main_lon", "magError", "depthError", "horizontalError", "nst", "gap", "dmin", 
    "rms", "magNst", "is_converted_mag", "lat_bin", "lon_bin", "b_value_daily", 
    "lag1_mag_max", "lag1_eq_count", "energia_lag1", "roll7_eq_count", "roll30_eq_count", 
    "roll7_mag_max", "roll30_mag_max", "roll7_energia", "roll30_energia", 
    "days_since_last_eq", "TARGET_mag_max_next_7d", "lat", "lon", "adj_num_eqs_x", 
    "adj_max_mag_x", "adj_num_eqs_y", "adj_max_mag_y", "adj_roll7_eq_count", 
    "adj_roll7_mag_max", "adj_roll30_energia", "adj_roll30_eq_count", "adj_roll30_mag_max"
]

scaler = StandardScaler()
df[listconti] = scaler.fit_transform(df[listconti])

# 4. Convertir lógicas a numéricas
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)


# Asegurar que la columna 'date' es de tipo datetime para permitir cortes temporales
df['date'] = pd.to_datetime(df['date'])
print(df['date'].dtype)

# 5. División en train y test por corte de tiempo
train = df[df['date'] < "2019-01-01"].copy()
test  = df[df['date'] >= "2019-01-01"].copy()
def compute_target_reg_enc_30d(df):
    # Hacer una copia y resetear índices
    df = df.copy().reset_index(drop=True)
    
    # Crear columna con NaN
    df['target_reg_enc_30d'] = np.nan
    
    # Procesar cada cell_id
    for cell_id in df['cell_id'].unique():
        # Obtener índices del grupo actual
        group_mask = df['cell_id'] == cell_id
        group_indices = df[group_mask].index
        
        # Si el grupo está vacío, continuar
        if len(group_indices) == 0:
            continue
        
        # Ordenar por fecha dentro del grupo
        group_df = df.loc[group_indices].sort_values('date')
        
        # Calcular rolling mean
        try:
            rolling_result = (
                group_df
                .set_index('date')['TARGET_mag_max_next_7d']
                .rolling('30D', closed='left')
                .mean()
            )
            
            # Asignar resultados
            df.loc[group_indices, 'target_reg_enc_30d'] = rolling_result.to_numpy()
            
        except Exception as e:
            print(f"Error procesando cell_id {cell_id}: {e}")
            # Fallback: usar media simple
            df.loc[group_indices, 'target_reg_enc_30d'] = (
                group_df['TARGET_mag_max_next_7d']
                .shift(1)
                .rolling(window=30, min_periods=1)
                .mean()
                .to_numpy()
            )
    
    return df

# Aplicar
train = compute_target_reg_enc_30d(train)
train['target_reg_enc_30d'].fillna(train['TARGET_mag_max_next_7d'].mean(), inplace=True)

test = compute_target_reg_enc_30d(test)
test['target_reg_enc_30d'].fillna(test['TARGET_mag_max_next_7d'].mean(), inplace=True)

datetime64[ns]

C:\Users\longj\AppData\Local\Temp\ipykernel_17740\1189971163.py:91: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['target_reg_enc_30d'].fillna(train['TARGET_mag_max_next_7d'].mean(), inplace=True)
C:\Users\longj\AppData\Local\Temp\ipykernel_17740\1189971163.py:94: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['target_reg_enc_30d'].fillna(test['TARGET_mag_max_next_7d'].mean(), inplace=True)

In [134]:
mi_lista = [
    "target_reg_enc_30d", "roll7_energia", "roll30_mag_max", "roll30_energia",
    "adj_roll30_mag_max", "gap", "roll7_eq_count", "roll30_eq_count",
    "locationSource_ci", "adj_roll30_energia", "main_depth", "eq_count",
    "rms", "days_since_last_eq", "lat"
]

In [135]:
# Preparar datos
X_train = train[mi_lista]
y_train = train["TARGET_mag_max_next_7d"]  # o TARGET_occurrence_M4.5 según el objetivo

X_test = test[mi_lista]
y_test = test["TARGET_mag_max_next_7d"]

In [136]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import make_scorer, mean_squared_error
param_grid = {
    'n_estimators': [150],
    'max_features': [8],
    'min_samples_leaf': [10],         # min.node.size
    'max_depth': [15]             # Profundidad máxima
}

mse_scorer = make_scorer(
    mean_squared_error,
    greater_is_better=False
)

tscv = TimeSeriesSplit(n_splits=5)
scoring = {
    'MSE': 'neg_mean_squared_error',
    'MAE': 'neg_mean_absolute_error', 
    'R2': 'r2'
}
# 4. Configurar GridSearchCV
grid_search = GridSearchCV(
    RandomForestRegressor(
        random_state=42,
        n_jobs=-1
    ),
    param_grid=param_grid,
    cv=tscv,
    scoring=scoring,
    n_jobs=-1,
    verbose=1,
    return_train_score=True
)

# 5. Ejecutar tuneo
print("🔍 Tuneando Random Forest...")
# asegurarse de que GridSearchCV re-fitee usando la métrica 'MSE' al usar scoring multi-métrica
grid_search.refit = 'MSE'
grid_search.fit(X_train, y_train)

print(f"\n✅ Mejores parámetros: {grid_search.best_params_}")
print(f"📊 Mejor MSE (validación): {grid_search.best_score_:.4f}")

# Evaluar en test
best_rf = grid_search.best_estimator_
y_pred = best_rf.predict(X_test)

🔍 Tuneando Random Forest...
Fitting 5 folds for each of 1 candidates, totalling 5 fits

✅ Mejores parámetros: {'max_depth': 15, 'max_features': 8, 'min_samples_leaf': 10, 'n_estimators': 150}
📊 Mejor MSE (validación): -0.2978

In [139]:
for data in (test_j, test_ch):
    if 'locationSource_ci' not in data.columns:
        data['locationSource_ci'] = (
            data['locationSource'].eq('ci').astype(int)
            if 'locationSource' in data.columns
            else 0
        )

    # Ensure all model features exist and contain no NaN values
    for col in mi_lista:
        if col not in data.columns:
            data[col] = 0

    data[mi_lista] = data[mi_lista].fillna(train[mi_lista].median())

pred_j = best_rf.predict(test_j[mi_lista])
pred_ch = best_rf.predict(test_ch[mi_lista])
test_ch['locationSource_ci'].fillna(0, inplace=True)
pred_j = best_rf.predict(test_j[mi_lista])
pred_ch = best_rf.predict(test_ch[mi_lista])

C:\Users\longj\AppData\Local\Temp\ipykernel_17740\3883064450.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_ch['locationSource_ci'].fillna(0, inplace=True)

In [140]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# 2. Función para calcular métricas base
def calcular_metricas(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    return {
            'RMSE': np.sqrt(mse),
            'MSE': mse,
            'MAE': mean_absolute_error(y_true, y_pred),
            'R2': r2_score(y_true, y_pred),
            'MAPE': np.mean(np.abs((y_true - y_pred) / y_true)) * 100  # Porcentaje
        }

In [147]:
test_j["TARGET_mag_max_next_7d"].fillna(0, inplace=True)
  # Verificar si hay valores nulos
test_ch["TARGET_mag_max_next_7d"].fillna(0, inplace=True)

C:\Users\longj\AppData\Local\Temp\ipykernel_17740\4015437615.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_ch["TARGET_mag_max_next_7d"].fillna(0, inplace=True)

In [148]:
metricas_j = calcular_metricas(test_j["TARGET_mag_max_next_7d"], pred_j)
metricas_ch = calcular_metricas(test_ch["TARGET_mag_max_next_7d"], pred_ch)

In [149]:
print(metricas_j)
print(metricas_ch)

{'RMSE': np.float64(1.956270379695192), 'MSE': 3.82699379847277, 'MAE': 1.8066711094675165, 'R2': -2.870838244609118, 'MAPE': np.float64(inf)}
{'RMSE': np.float64(1.966311906455689), 'MSE': 3.8663825134694063, 'MAE': 1.8258425196206112, 'R2': -2.9106782214796953, 'MAPE': np.float64(inf)}